---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: hello
  namespace: test
  labels:
    chart: hello
  annotations:
    flux.weave.works/tag.chart-image: glob:prod
spec:
  chartGitPath: hello
  releaseName: hello
  values:
    image: sorenmat/hello:1
    imagePullPolicy: IfNotPresent
